# Cops that don't apply within ERB files.

Layout/ArgumentAlignment:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LeadingEmptyLines:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false
