name: reviewdog

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning
          locale: "UK"

  erb-lint:
    name: runner / erb-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          ruby-version: '3.1.4' # Specify your Ruby version here
      - uses: tk0miya/action-erblint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning
          use_bundler: true

  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          ruby-version: '3.1.4' # Specify your Ruby version here
      - name: Install Bundler
        run: gem install bundler
      - name: Run RuboCop with reviewdog
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile
          rubocop_flags: '-f json' # Ensure RuboCop outputs in JSON format
          github_token: ${{ secrets.GITHUB_TOKEN }}
