name: Test Action

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run tests against
        type: environment
        required: true
        default: Test
      skip-tests:
        description: Skip tests?
        type: boolean
        default: false

run-name: Pre-prod - Deploying ${{ github.ref_name }} branch to ${{ inputs.environment }}

jobs:
  env-check:
    name: Pre-Prod check

    runs-on: ubuntu-latest
    steps:
      - name: Check failed
        if: ${{ contains(inputs.environment, 'Prod') }}
        uses: actions/github-script@v7
        with:
          script: core.setFailed('Invalid environment ("${{ inputs.environment }}"), only pre-prod environments can run this workflow')

  test:
    name: Tests
    needs: env-check

    runs-on: ubuntu-latest
    steps:
      - name: Skip
        if: ${{ inputs.skip-tests }}
        uses: actions/github-script@v7
        with:
          script: core.setFailed('Invalid environment ("${{ inputs.environment }}"), only pre-prod environments can run this workflow')
        run: | 
          echo "Skipping tests"
          exit 0
      - name: Run
        if: ${{ !inputs.skip-tests }}
        run: echo "Running tests"
    
  display-variables:
    name: My super duper test input - ${{ inputs.environment }}
    needs: [env-check, test]
    environment: ${{ inputs.environment }}

    runs-on: ubuntu-latest
    steps:
    - name: Use variables
      run: |
        echo "${{ secrets.MY_SECRET }}" | sed "s/./& /g"
        echo ${{ inputs.environment }}
        echo ${{ vars.ENV_NAME }}
