name: Test Action

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: Test

jobs:
  display-variables:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
    - name: Use variables
      run: |
        echo ${{ env.ENV_NAME }}
