name: Test Action

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: Test
      skip-tests:
        description: 'Skip tests?'
        type: boolean
        default: false

jobs:
  env-check:
    name: Pre-Prod check
    runs-on: ubuntu-latest
    if: "contains(inputs.environment, 'Prod')"
    steps:
      - run: echo 'Invalid environment, only pre-prod environments can run this workflow'
      - run: exit 1

  test:
    if: "!inputs.skip-tests"
    runs-on: ubuntu-latest
    steps:
      - run: echo Running tests
    
    
  display-variables:
    needs: [test]
    if: ${{ always() && needs.test.result != 'failure' && !contains(inputs.environment, 'Prod') }}
    name: My super duper test input - ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Use variables
      run: |
        echo "${{ secrets.MY_SECRET }}" | sed 's/./& /g'
        echo ${{ inputs.environment }}
        echo ${{ vars.ENV_NAME }}
